   ![](http://tectijuana.edu.mx/wp-content/uploads/2014/11/Heading-Ing-sistemas-2048x672.png),
   # Iniciarás con Markdown (MD) las generales del Notebook
   ## 25 - conjugate gradiets_MarianaCuevas
   ##  Mariana Cuevas Verdi
   ## 01/Sep/2017

In [1]:
import numpy as np

# algorithm

In [2]:
def conjugate_gradients(A, b):
    x = np.zeros(A.shape[1])
    residuals = b - A @ x
    direction = residuals
    error = residuals.T @ residuals

    # step along conjugate directions
    while error > 1e-8:
        x += direction * error / (direction.T @ A @ direction)
        residuals = b - A @ x
        error1 = error
        error = residuals.T @ residuals
        direction = residuals + error / error1 * direction

    return x

# run

In [3]:
A = np.random.rand(5, 3)
b = np.random.rand(5)

print('A')
print(A)
print('b')
print(b)
print('x')

# make system positive semidefinite
print(conjugate_gradients(A.T @ A, A.T @ b))

A
[[ 0.37990883  0.92294044  0.67164625]
 [ 0.42807927  0.44805243  0.53073921]
 [ 0.29523096  0.76412767  0.65122319]
 [ 0.08975785  0.24060581  0.19552723]
 [ 0.10713974  0.45195138  0.72937303]]
b
[ 0.90580283  0.64244399  0.36284661  0.93906905  0.68193386]
x
[ 0.39585448  0.23116662  0.67241497]
