   ![](http://tectijuana.edu.mx/wp-content/uploads/2014/11/Heading-Ing-sistemas-2048x672.png),
   # Iniciarás con Markdown (MD) las generales del Notebook
   ## 30 - strassen multiplication_MarianaCuevas
   ##  Mariana Cuevas Verdi
   ## 01/Sep/2017

In [1]:
import numpy as np

# algorithm

In [2]:


def strassen(A, B):
    k = A.shape[0] // 2
    if k == 0:
        return A * B

    A11, A12 = A[:k, :k], A[:k, k:]
    A21, A22 = A[k:, :k], A[k:, k:]
    B11, B12 = B[:k, :k], B[:k, k:]
    B21, B22 = B[k:, :k], B[k:, k:]
    
    T1 = strassen(A11 + A22, B11 + B22)
    T2 = strassen(A21 + A22, B11)
    T3 = strassen(A11, B12 - B22)
    T4 = strassen(A22, B21 - B11)
    T5 = strassen(A11 + A12, B22)
    T6 = strassen(A21 - A11, B11 + B12)
    T7 = strassen(A12 - A22, B21 + B22)
    
    C = np.zeros(A.shape, dtype=A.dtype)
    C[:k, :k] = T1 + T4 - T5 + T7
    C[:k, k:] = T3 + T5
    C[k:, :k] = T2 + T4
    C[k:, k:] = T1 - T2 + T3 + T6
    
    return C



# run

In [3]:
X = np.random.randint(0, 10, (8, 8))
X

array([[4, 6, 1, 5, 3, 0, 1, 9],
       [0, 4, 8, 4, 9, 0, 9, 4],
       [3, 1, 7, 7, 6, 4, 6, 2],
       [1, 2, 0, 1, 2, 8, 0, 0],
       [4, 5, 1, 0, 3, 3, 5, 0],
       [8, 1, 6, 8, 5, 3, 3, 9],
       [4, 9, 4, 0, 9, 3, 6, 8],
       [6, 5, 3, 3, 4, 5, 1, 4]])

In [4]:
Y = np.random.randint(0, 10, (8, 8))
Y

array([[9, 6, 2, 9, 9, 5, 6, 2],
       [8, 2, 4, 9, 0, 5, 4, 5],
       [3, 3, 7, 2, 1, 2, 4, 3],
       [8, 6, 8, 0, 2, 7, 2, 8],
       [0, 5, 5, 0, 8, 2, 2, 1],
       [1, 9, 7, 6, 9, 4, 6, 3],
       [8, 3, 8, 1, 4, 6, 6, 2],
       [3, 4, 4, 8, 5, 2, 2, 3]])

In [5]:
strassen(X, Y)

array([[162, 123, 138, 165, 120, 117,  92, 113],
       [172, 144, 237,  93, 144, 144, 136, 115],
       [170, 175, 229,  96, 166, 151, 140, 124],
       [ 41,  98,  84,  75,  99,  58,  68,  46],
       [122,  94, 111, 106, 108,  95, 102,  58],
       [216, 213, 232, 186, 218, 171, 156, 150],
       [195, 176, 218, 213, 203, 155, 164, 119],
       [152, 157, 156, 168, 164, 124, 126, 103]])